 ### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# np.array => Vector
import numpy as np 
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
# 2D array => Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3D array => Tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# dtype 
print(np.array([1,2,3], dtype=float))
np.array([1,2,3], dtype=complex) #iski jrurt nhi padti per apan yeh bhi kar skte hai 

[1. 2. 3.]


array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
# np.arange
print(np.arange(1,11))
print(np.arange(1,11,2))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [21]:
# with reshape  
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
# np.ones
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
# np.zeros  
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# np.random -> 0,1 ke bich bnaata hai
np.random.random((3,4))

array([[0.26373314, 0.63458045, 0.79364178, 0.26028962],
       [0.1686493 , 0.11506936, 0.38326247, 0.56899291],
       [0.21353582, 0.41005954, 0.226805  , 0.01834107]])

In [36]:
# np.linspace -> linear space  
# np.linspace(lower,upper,no_elements)
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [35]:
# np.identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [3]:
a1 = np.arange(10) 
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
# ndim 
a3.ndim

3

In [5]:
# shape 
print(a3.shape) # (row,columns)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
# size 
print(a2.size) 
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [22]:
# itemsize 
print(a1.itemsize)


8


In [23]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


### Changing Datatype 

In [32]:
# astype => size kam krne ke liye use kiya jata hai 
a3.astype(np.int32)     
print(a3.dtype)

int64


### Array Operations

In [38]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# scalar operation 
# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [40]:
# relational operator 
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
# Vector operation  
# Arithmetic 
a1 * a2 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array function 

In [45]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[24., 84.,  3.],
       [87., 37., 60.],
       [40., 38., 60.]])

In [47]:
# max/min/sum/prod 
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

87.0
3.0
433.0
106531697664000.0


In [50]:
# max/min/sum/prod 
# 0-> col and 1-> row
print(np.max(a1,axis=0))
print(np.min(a1,axis=1))

[87. 84. 60.]
[ 3. 37. 38.]


In [54]:
# mean/median/std/var  
print(np.mean(a1,axis=1))
print(np.median(a1,axis=0))
print(np.std(a1))
print(np.var(a1,axis=0))

[37.         61.33333333 46.        ]
[40. 38. 60.]
25.800277537027664
[714.88888889 480.66666667 722.        ]


In [55]:
# trignometric function  
np.sin(a1)

array([[-0.90557836,  0.73319032,  0.14112001],
       [-0.82181784, -0.64353813, -0.30481062],
       [ 0.74511316,  0.29636858, -0.30481062]])

In [57]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(4,3)
np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [59]:
# log and exponents 
np.log(a1)
np.exp(a1)

array([[2.64891221e+10, 3.02507732e+36, 2.00855369e+01],
       [6.07603023e+37, 1.17191424e+16, 1.14200739e+26],
       [2.35385267e+17, 3.18559318e+16, 1.14200739e+26]])

In [66]:
# round/floor/ciel
a = np.random.random((2,3))*100
np.ceil(a)

array([[73., 80., 89.],
       [91., 14., 70.]])

### indexing and slicing 

In [18]:
a1 = np.arange(10) 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) #(2ds,row, columns)

In [9]:
a1, a2, a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [7]:
a1[1], a1[-1]

(np.int64(1), np.int64(9))

In [12]:
# a2[row,column]
a2[1][2]

np.int64(6)

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
a3[1,0,1]
a3[0,1,0]
a3[1,1,0]

np.int64(6)

In [20]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a1[2:5]

array([2, 3, 4])

In [22]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a2[0,:]

array([0, 1, 2, 3])

In [28]:
a2[:,2]

array([ 2,  6, 10])

In [32]:
a2[1:,1:3] #a[row,column]

array([[ 5,  6],
       [ 9, 10]])

In [34]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [37]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [38]:
a2[1,::3]

array([4, 7])

In [39]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [41]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [43]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
a3[0,1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [45]:
a3[1,:,1]

array([10, 13, 16])

In [46]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [47]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### iterating 

In [48]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [53]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [54]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [56]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [58]:
# reshape

In [68]:
# transpose 
a = np.arange(8).reshape(2,4)
np.transpose(a)
a.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [69]:
# ravel 
a2 = np.arange(12).reshape(3,4)
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### stacking 

In [8]:
# horizontal stacking 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [13]:
# vertical stacking 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4) 
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### spliting 

In [11]:
# horizontal spliting 
print(a1)
np.hsplit(a1,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [14]:
# vertical spliting 
print(a2)
np.vsplit(a2,3)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]