#### np.sort()

In [35]:
import numpy as np 

In [36]:
a = np.random.randint(1,100,15) 
print(a) 
print('------------')
print(np.sort(a))
print('------------')
print(np.sort(a)[::-1])

[97 40 15 91 95 42 30 93 46 59 78 19 74 69  7]
------------
[ 7 15 19 30 40 42 46 59 69 74 78 91 93 95 97]
------------
[97 95 93 91 78 74 69 59 46 42 40 30 19 15  7]


In [37]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b) 
print('------------')
print(np.sort(b)) # -> row wise 
print('------------')
print(np.sort(b, axis=0)) # -> column wise

[[25 57  1 13]
 [79 68 30 22]
 [62 69 35 76]
 [75 44 54 24]
 [23 27 96 90]
 [69 70 79 68]]
------------
[[ 1 13 25 57]
 [22 30 68 79]
 [35 62 69 76]
 [24 44 54 75]
 [23 27 90 96]
 [68 69 70 79]]
------------
[[23 27  1 13]
 [25 44 30 22]
 [62 57 35 24]
 [69 68 54 68]
 [75 69 79 76]
 [79 70 96 90]]


#### np.append()

In [38]:
print(a)
np.append(a,100)

[97 40 15 91 95 42 30 93 46 59 78 19 74 69  7]


array([ 97,  40,  15,  91,  95,  42,  30,  93,  46,  59,  78,  19,  74,
        69,   7, 100])

In [39]:
print(b)
print('======================')
np.append(b,np.ones((b.shape[0],1)),axis=1)

[[25 57  1 13]
 [79 68 30 22]
 [62 69 35 76]
 [75 44 54 24]
 [23 27 96 90]
 [69 70 79 68]]


array([[25., 57.,  1., 13.,  1.],
       [79., 68., 30., 22.,  1.],
       [62., 69., 35., 76.,  1.],
       [75., 44., 54., 24.,  1.],
       [23., 27., 96., 90.,  1.],
       [69., 70., 79., 68.,  1.]])

### np.concatenate

In [40]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a) 
print(b) 

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [41]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
np.concatenate((a,b), axis=1) #-> column wise 

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [43]:
a = np.random.randint(1,10,10)
print(a)

[8 6 5 6 7 5 7 7 5 6]


In [44]:
np.unique(a)

array([5, 6, 7, 8], dtype=int32)

### np.expend_dims

In [45]:
a = np.random.randint(1,10,10)
print(a)
a.shape

[8 5 7 3 2 1 9 5 5 9]


(10,)

In [46]:
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=0).shape)

[[8 5 7 3 2 1 9 5 5 9]]
(1, 10)


In [47]:
print(np.expand_dims(a,axis=1))

[[8]
 [5]
 [7]
 [3]
 [2]
 [1]
 [9]
 [5]
 [5]
 [9]]


### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [48]:
a = np.random.randint(1,100,8)
a

array([27, 70, 18, 57, 96, 41, 54, 35], dtype=int32)

In [49]:
# find the all indices with value greater then 50 
np.where(a>50)

(array([1, 3, 4, 6]),)

In [50]:
# replace all values>50 with 0 
# np.where(condition, true, false)
np.where(a<50, 0, a)

array([ 0, 70,  0, 57, 96,  0, 54,  0], dtype=int32)

In [51]:
# replace evens into zero
np.where(a%2==0, 0, a)

array([27,  0,  0, 57,  0, 41,  0, 35], dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [73]:
a=np.random.randint(1,100,10)
a

array([51, 77, 80, 86, 17, 32, 14, 43,  8, 47], dtype=int32)

In [53]:
np.argmax(a)

np.int64(9)

In [54]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[85, 43, 28, 61],
       [17, 84, 41, 51],
       [98, 98, 36, 12],
       [53, 33, 33, 23],
       [ 9, 70, 28, 69],
       [83, 57, 85, 90]], dtype=int32)

In [55]:
np.argmax(b, axis=1) ## row wise

array([0, 1, 0, 0, 1, 3])

In [56]:
np.argmin(a)

np.int64(8)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [57]:
a

array([42, 56, 25, 37, 56, 57, 44, 57,  8, 89], dtype=int32)

In [58]:
np.cumsum(a)

array([ 42,  98, 123, 160, 216, 273, 317, 374, 382, 471])

In [59]:
b

array([[85, 43, 28, 61],
       [17, 84, 41, 51],
       [98, 98, 36, 12],
       [53, 33, 33, 23],
       [ 9, 70, 28, 69],
       [83, 57, 85, 90]], dtype=int32)

In [60]:
np.cumsum(b,axis=0)

array([[ 85,  43,  28,  61],
       [102, 127,  69, 112],
       [200, 225, 105, 124],
       [253, 258, 138, 147],
       [262, 328, 166, 216],
       [345, 385, 251, 306]])

In [61]:
np.cumsum(b)

array([  85,  128,  156,  217,  234,  318,  359,  410,  508,  606,  642,
        654,  707,  740,  773,  796,  805,  875,  903,  972, 1055, 1112,
       1197, 1287])

In [62]:
np.cumprod(a)

array([               42,              2352,             58800,
                 2175600,         121833600,        6944515200,
            305558668800,    17416844121600,   139334752972800,
       12400793014579200])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [63]:
a

array([42, 56, 25, 37, 56, 57, 44, 57,  8, 89], dtype=int32)

In [64]:
np.percentile(a,100)

np.float64(89.0)

In [65]:
np.percentile(a,50) 

np.float64(50.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [66]:
a

array([42, 56, 25, 37, 56, 57, 44, 57,  8, 89], dtype=int32)

In [67]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 0, 1, 1, 2, 4, 0, 0, 1, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [68]:
salary = np.random.randint(20000,100000, 8)
experience = np.random.randint(1,5,8, dtype='int')

In [69]:
np.corrcoef(salary,experience)

array([[1.        , 0.20163495],
       [0.20163495, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [70]:
a

array([42, 56, 25, 37, 56, 57, 44, 57,  8, 89], dtype=int32)

In [71]:
items = [10,20,30,40,50,60,70,80,90,100]

In [74]:
a[np.isin(a,items)]

array([80], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [75]:
a

array([51, 77, 80, 86, 17, 32, 14, 43,  8, 47], dtype=int32)

In [76]:
np.flip(a)

array([47,  8, 43, 14, 32, 17, 86, 80, 77, 51], dtype=int32)

In [77]:
b

array([[85, 43, 28, 61],
       [17, 84, 41, 51],
       [98, 98, 36, 12],
       [53, 33, 33, 23],
       [ 9, 70, 28, 69],
       [83, 57, 85, 90]], dtype=int32)

In [79]:
np.flip(b)

array([[90, 85, 57, 83],
       [69, 28, 70,  9],
       [23, 33, 33, 53],
       [12, 36, 98, 98],
       [51, 41, 84, 17],
       [61, 28, 43, 85]], dtype=int32)

In [80]:
np.flip(b, axis=0)

array([[83, 57, 85, 90],
       [ 9, 70, 28, 69],
       [53, 33, 33, 23],
       [98, 98, 36, 12],
       [17, 84, 41, 51],
       [85, 43, 28, 61]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [81]:
a

array([51, 77, 80, 86, 17, 32, 14, 43,  8, 47], dtype=int32)

In [85]:
np.put(a,[0,1],[110,530])  #-> permanent change krta hai put(array, condition, changes)

In [86]:
a

array([110, 530,  80,  86,  17,  32,  14,  43,   8,  47], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [87]:
a

array([110, 530,  80,  86,  17,  32,  14,  43,   8,  47], dtype=int32)

In [89]:
np.delete(a,[0,2,4])

array([530,  86,  32,  14,  43,   8,  47], dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [90]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [91]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
np.intersect1d(m,n)

array([3, 4, 5])

In [93]:
np.setdiff1d(m,n)

array([1, 2])

In [94]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [97]:
m[np.in1d(m,1)]

C:\Users\pc\AppData\Local\Temp\ipykernel_20248\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [98]:
a

array([110, 530,  80,  86,  17,  32,  14,  43,   8,  47], dtype=int32)

In [102]:
np.clip(a,a_min=40,a_max=100)

array([100, 100,  80,  86,  40,  40,  40,  43,  40,  47], dtype=int32)